---
- name: Minimal NVM installation for root user
  hosts: localhost
  connection: local
  become: yes

  vars:
    # Узнать версию nvm можно тут https://github.com/nvm-sh/nvm
    nvm_version: "v0.40.3" # Можно указать актуальную версию NVM
    nvm_install_dir: "/usr/local/nvm"
    default_user: "root"
    nvm_bashrc_path: "/root/.bashrc"
    node_version: "lts/fermium"  # Node.js 14.x

  tasks:
    - name: Create NVM directory
      file:
        path: "{{ nvm_install_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ default_user }}"
        group: "{{ default_user }}"

    - name: Install NVM
      shell: |
        curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | PROFILE=/dev/null bash
        echo 'export NVM_DIR="{{ nvm_install_dir }}"' >> "{{ nvm_bashrc_path }}"
        echo '[ -s "{{ nvm_install_dir }}/nvm.sh" ] && \. "{{ nvm_install_dir }}/nvm.sh"' >> "{{ nvm_bashrc_path }}"
      args:
        executable: /bin/bash
      environment:
        NVM_DIR: "{{ nvm_install_dir }}"
